# ID
hf_username: Synthyra
hf_token: null
synthyra_api_key: null
wandb_api_key: null

# Paths
yaml_path: null
log_dir: logs
results_dir: results
data_paths:
  - DeepLoc-2
model_save_dir: weights
embedding_save_dir: embeddings
download_dir: Synthyra/mean_pooled_embeddings
replay_path: null

# DataArguments:
data_dirs:
  # - EC
  - DeepLoc-2
  #- DeepLoc-10
  #- enzyme-kcat
  #- human-ppi
delimiter: ','
col_names:
  - seqs
  - labels
max_length: 1024
trim: false


# BaseModelArguments:
model_names:
  - ESM2-8
  # - ESM2-35
  # - ESM2-150
  # - ESM2-650
  # - ESM2-3B
  # - ESMC-300
  # - ESMC-600
  # - Random
  # - Random-Transformer


# ProbeArguments:
probe_type: linear  # valid options: linear, transformer, crossconv
tokenwise: false
hidden_dim: 8192
dropout: 0.2
n_layers: 1
pre_ln: true
classifier_dim: 4096
transformer_dropout: 0.1
classifier_dropout: 0.2
n_heads: 4
rotary: true
pooling_types:
  - cls
  # - mean


# EmbeddingArguments:
embedding_batch_size: 4
num_workers: 0
download_embeddings: false
matrix_embed: false
embedding_pooling_types:
  - mean
  # - var
save_embeddings: false
embed_dtype: float16
sql: false


# TrainerArguments:
model_save_dir: 
num_epochs: 200
trainer_batch_size: 64
gradient_accumulation_steps: 1
lr: 1e-4
weight_decay: 0.00
patience: 3
seed: 42
