# DataArguments:
data_dirs:
  # - EC
  - DeepLoc-2
  #- DeepLoc-10
  #- enzyme-kcat
  #- human-ppi
delimiter: ','
col_names:
  - seqs
  - labels
max_len: 1024
trim: false


# BaseModelArguments:
model_names:
  - ESM2-8
  #- ESM2-35
  #- ESM2-150
  # - ESM2-650
  # - ESM2-3B
  # - ESMC-300
  # - ESMC-600
  # - Random
  # - Random-Transformer


# ProbeArguments:
probe_type: linear  # valid options: linear, transformer, crossconv
tokenwise: false
hidden_dim: 8192
dropout: 0.2
n_layers: 1
pre_ln: true
ff_dim: 4096
transformer_dropout: 0.1
classifier_dropout: 0.2
n_heads: 4
rotary: true
pooling_types:
  - cls
  # - mean


# EmbeddingArguments:
batch_size: 4
num_workers: 0
download_embeddings: false
download_dir: Synthyra/mean_pooled_embeddings
matrix_embed: false
pooling_types:
  - mean
  # - var
save_embeddings: false
embed_dtype: float16
sql: false
save_dir: embeddings


# TrainerArguments:
output_dir: Synthyra/probes
num_epochs: 200
batch_size: 64
gradient_accumulation_steps: 1
lr: 1e-4
patience: 3
