# ID
hf_username: Synthyra
hf_token: null
synthyra_api_key: null
wandb_api_key: null


# Paths
yaml_path: null
log_dir: logs
results_dir: results
model_save_dir: weights
embedding_save_dir: embeddings
download_dir: Synthyra/mean_pooled_embeddings
plots_dir: plots
replay_path: null
pretrained_probe_path: null


# DataArguments:
delimiter: ','
col_names:
  - seqs
  - labels
max_length: 1024
trim: false
data_names:
  - DeepLoc-2
  - DeepLoc-10
  - EC
  - GO-CC
  - GO-BP
  - GO-MF
  - MB
  - enzyme-kcat
  - solubility
  - localization
  - temperature-stability
  - peptide-HLA-MHC-affinity
  - optimal-temperature
  - optimal-ph
  - material-production
  - fitness-prediction
  - number-of-folds
  - cloning-clf
  - stability-prediction
  - human-ppi
  - human-ppi-pinui
  - yest-ppi-pinui
  - shs27-ppi
  - shs148-ppi
  - PPA-ppi

data_dirs: []


# BaseModelArguments:
model_names:
  - ESM2-8
  - ESM2-35
  - ESM2-150
  - ESM2-650
  - ESM2-3B
  - ESMC-300
  - ESMC-600
  - Random
  - Random-Transformer


# ProbeArguments:
probe_type: linear  # valid options: linear, transformer, crossconv
tokenwise: false
hidden_dim: 8192
dropout: 0.2
n_layers: 1
pre_ln: true
classifier_dim: 4096
transformer_dropout: 0.1
classifier_dropout: 0.2
n_heads: 4
rotary: true
probe_pooling_types:
  - mean
  - cls
save_model: false
production_model: false
use_lora: false
lora_r: 8
lora_alpha: 32.0
lora_dropout: 0.01


# ScikitArguments:
scikit_n_iter: 10
scikit_cv: 3
scikit_random_state: 42
scikit_model_name: null
use_scikit: false
n_jobs: 1


# EmbeddingArguments:
embedding_batch_size: 8
num_workers: 0
download_embeddings: false
matrix_embed: false
embedding_pooling_types:
  - mean
save_embeddings: false
embed_dtype: float32
sql: false


# TrainerArguments:
num_epochs: 200
probe_batch_size: 64
base_batch_size: 4
probe_grad_accum: 1
base_grad_accum: 8
lr: 1e-4
weight_decay: 0.00
patience: 5
seed: 42
full_finetuning: false
hybrid_probe: false
